[RAIN-2830] Added extraVolumes and port information in certificate-ve…
egovernments/DIGIT-DevOps pull request #206
Opened 2021-07-12 12:56 UTC by shashwat-egov

…rification deployment config

2021-07-12 13:01 UTC, talele08 requested changes

2021-07-12 13:01 UTC, talele08 commented on deploy-as-code/helm/charts/utilities/certificate-verification/values.yaml
> +  - name: certificate-verification
js-injection

2021-07-12 13:08 UTC, talele08 approved these changes

2021-07-12 13:09 UTC, sathishp-eGov approved these changes

2021-07-12 13:31 UTC, nikesh-eGov reviewed
Add subfilter-injection-configmap temp.
https://github.com/egovernments/DIGIT-DevOps/blob/master/deploy-as-code/helm/charts/frontend/digit-ui/templates/subfilter-injection-configmap.yaml

2021-07-12 13:42 UTC, nikesh-eGov approved these changes

2021-07-12 14:12 UTC, sathishp-eGov approved these changes

2021-07-13 02:38 UTC, sathishp-eGov approved these changes

2021-07-13 04:48 UTC, merged