[PI-1721]-Added valuefirst key to read the basic authentication heade…
egovernments/DIGIT-DevOps pull request #261
Opened 2021-08-05 08:19 UTC by mahammadnizam-wt-eGov

…r from configs

2021-08-05 12:11 UTC, ramakrishnaippili-eGov approved these changes

2021-08-05 12:12 UTC, ramakrishnaippili-eGov approved these changes

2021-08-05 12:12 UTC, ramakrishnaippili-eGov approved these changes

2021-08-05 13:11 UTC, elzanmathew-eGov approved these changes

2021-08-06 02:50 UTC, gajendran-egov requested changes
Move this to secret

2021-08-06 05:16 UTC, gajendran-egov approved these changes

2021-08-06 05:16 UTC, merged