HLM-5700 adding helm chart for resource-estimation-service
egovernments/DIGIT-DevOps pull request #2678
Opened 2024-05-09 11:59 UTC by Priyanka-eGov

2024-05-09 12:01 UTC, shashwat-egov requested changes

2024-05-09 12:01 UTC, shashwat-egov commented on deploy-as-code/helm/charts/health-services/resource-estimation-service/values.yaml
why is zuul required for resource estimation utility?

2024-05-09 12:12 UTC, Priyanka-eGov commented on deploy-as-code/helm/charts/health-services/resource-estimation-service/values.yaml
Have disabled zuul and ingress

2024-05-13 05:14 UTC, shashwat-egov approved these changes

2024-05-13 05:14 UTC, shashwat-egov approved these changes

2024-05-13 05:14 UTC, merged