added environment variables
egovernments/DIGIT-DevOps pull request #587
Opened 2022-01-12 07:01 UTC by shubhang-eGov

2022-01-12 07:04 UTC, rohit-eGov approved these changes

2022-01-12 07:14 UTC, rushang7-eGov requested changes

2022-01-12 07:14 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/core-services/egov-url-shortening/values.yaml
> +    value: {{ index .Values "egov-url-shorten-hashid-salt" | quote}}
No need for "egov-url-shorten-" prefix.

2022-01-12 07:14 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/core-services/egov-url-shortening/values.yaml
> +    value: {{ index .Values "egov-url-shorten-hashid-min-length" | quote}}
To maintain uniformity, append _S_ to the variable name _hashid_. The the variable name would become **hashids-min-length**

2022-01-12 07:14 UTC, rushang7-eGov commented on deploy-as-code/helm/environments/dev.yaml
> +  egov-url-shorten-hashid-min-length: "5"
Does dev cluster need 5? Or would 4 work.

2022-01-12 07:14 UTC, rushang7-eGov commented on deploy-as-code/helm/charts/core-services/egov-url-shortening/values.yaml
> +  - name: HASHIDS_SALT
Surround these two env vars with if condition.

2022-01-12 07:31 UTC, rushang7-eGov approved these changes

2022-02-17 08:39 UTC, sathishp-eGov approved these changes

2022-02-17 08:39 UTC, merged