RAIN-6580:birth certificate API ingest
egovernments/DIGIT-DevOps pull request #806
Opened 2022-04-27 04:33 UTC by kokila-eGov

RAIN-6580:birth certificate API ingest

2022-04-28 06:21 UTC, shashwat-egov requested changes

2022-04-28 06:21 UTC, shashwat-egov commented on deploy-as-code/helm/environments/dev.yaml
> +"BIRTH":{"totalBirthApplication":"number","totalCollection":"number","totalDownloadsByMobileApp":"number","totalDownloadsByWeb":"number","totalDownloads":"number","delayedRegistration":"number"}}'
Can you change totalBirthApplication to totalBirthApplications? Seems more intuitive that way.

2022-04-29 08:54 UTC, kokila-eGov reviewed
Birth and death API ingest changes made

2022-04-29 10:17 UTC, shashwat-egov requested changes
Please do the changes to the ingest metrics as discussed on slack to make the metrics intuitive.

2022-04-29 11:02 UTC, shashwat-egov approved these changes

2022-04-29 11:07 UTC, sathishp-eGov approved these changes

2022-04-29 11:08 UTC, merged